name: Cypress Tests

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        
      - name: Upload screenshots
        uses: actions/upload-artifact@v3.1.3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots